version: '3.1'

services:
  mta:
    build:
      context: .
      dockerfile: Dockerfile-mta
    volumes:
      - ./mail:/var/spool/postfix

  pubsub:
    build:
      context: .
      dockerfile: Dockerfile-pubsub
    volumes:
      - ./app:/nymph
      - ./db_data:/db
    command: ["php", "/nymph/pubsub.php"]
    ports:
      - "8081:8080"

  web:
    depends_on:
      - mta
      - pubsub
    build:
      context: .
      dockerfile: Dockerfile-web
    volumes:
      - ./app:/var/www/html
      - ./db_data:/db
      - ./maintenance:/maintenance
    ports:
      - "8080:80"
    environment:
      PUBSUB_HOST: pubsub:8080
