version: '3.1'

services:
  db:
    image: postgres:10
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: nymph
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

  mta:
    build:
      context: .
      dockerfile: Dockerfile-mta
    volumes:
      - ./mail:/var/spool/postfix

  pubsub:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile-pubsub
    volumes:
      - ./app:/nymph
    command: ["./wait-for-it.sh", "db:5432", "-t", "120", "--", "./wait-and-run.sh"]
    ports:
      - "8081:8080"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: nymph
      POSTGRES_USER: nymph
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      TILMELD_SECRET_FILE: /run/secrets/tilmeld_secret
    secrets:
      - db_password
      - tilmeld_secret

  web:
    depends_on:
      - db
      - mta
      - pubsub
    build:
      context: .
      dockerfile: Dockerfile-web
    volumes:
      - ./app:/var/www/html
      - ./maintenance:/maintenance
    ports:
      - "8080:80"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: nymph
      POSTGRES_USER: nymph
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      PUBSUB_HOST: pubsub:8080
      TILMELD_SECRET_FILE: /run/secrets/tilmeld_secret
    secrets:
      - db_password
      - tilmeld_secret


secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt
  tilmeld_secret:
    file: tilmeld_secret.txt
